### ISSUE TITLE
Selenium tests

### ISSUE THREAD

**Issue by pantaoran** [mageinferno/docker-magento2-setup#4]
Have you ever tried to run selenium tests with this configuration?
I'm just trying this for the first time with any Magento 2 setup and it's not working, so I wonder if the problem is the container layout or something else that I'm not getting.

I added a selenium server container and linked it to the php container. I tried following the [instructions in the official docs](http://devdocs.magento.com/guides/v2.0/mtf/mtf_quickstart/mtf_quickstart_config.html) but so far no luck.

**Comment by markoshust** [comment]
I'll need some more info to go on here -- what exactly isn't working, errors happening, etc.

**Comment by pantaoran** [comment]
I'm working on this myself, it's been on hold for a few days now but hopefully I will figure it out before the end of the week. I just wanted to know if you had already tried this. If you have I will happily provide you with exact problem description, if you haven't then no big deal I'll figure it out eventually.

**Comment by markoshust** [comment]
Yea, sorry haven't done anything with these images and any testing yet. If you figure anything out, let me know!

**Comment by markoshust** [comment]
@pantaoran Let me know if you figured this out, would make a great addition! I'm not exactly sure how the selenium tests run and/or if this would be best run as a separate container.

**Comment by pantaoran** [comment]
When I opened this it looked like I'd soon be able to spend the time to figure it out. This will also be my first time to work with Selenium.
Unfortunately now we got another time-sensitive project in which is not Magento-based, so I'm guessing I won't be able to come back to this before Feb-March...

**Comment by markoshust** [comment]
No prob! I'll close this for now, as everything like this is really a WIP. Feel free to reopen if you have this implemented (I'll do the same).
